global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'sensorvision-monitor'
    environment: 'production'

scrape_configs:
  # SensorVision Backend Metrics
  - job_name: 'sensorvision-backend'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['backend:8080']
        labels:
          application: 'sensorvision'
          instance: 'backend'

  # Prometheus Self-Monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
